"""
apply.py — applies a machine-composed design system onto an existing project CSS.
Surgical by design: removes detected tells, replaces them with composed material,
layers composed tokens/motion underneath. Keeps every class name intact so
existing components keep working. Reports every change for review.
"""
import re
import json


def remove_tells(css):
    removed = []
    lines = css.splitlines()
    out = []
    for i, line in enumerate(lines):
        stripped = line.strip().lower()
        if stripped.startswith("backdrop-filter") and "blur(" in stripped:
            removed.append({"line": i + 1, "was": line.strip(), "tell": "mat.glassmorphism"})
            continue
        out.append(line)
    return "\n".join(out), removed


def fix_glass_card(css):
    pattern = re.compile(r"\.glass-card\s*\{[^}]*\}", re.S)
    m = pattern.search(css)
    if not m:
        return css, False
    replacement = (".glass-card {\n"
                   "  background: var(--surface-2, rgba(20, 17, 13, 0.92));\n"
                   "  border: 1px solid rgba(200, 153, 104, 0.12);\n"
                   "  box-shadow: var(--shadow-sheet, 0 1px 2px rgba(90, 60, 20, 0.10));\n"
                   "}")
    return css[:m.start()] + replacement + css[m.end():], True


def inject_composed_layer(css, composed_tokens, composed_motion):
    existing_vars = set(re.findall(r"(--[a-z0-9-]+)\s*:", css))
    lines_out = []
    added = []
    for line in composed_tokens.splitlines():
        m = re.match(r"\s*(--[a-z0-9-]+)\s*:", line)
        if m:
            name = m.group(1)
            if name in existing_vars:
                continue  # project owns this variable; never override
            lines_out.append(line)
            if name not in added:
                added.append(name)
        else:
            lines_out.append(line)
    block = []
    block.append("")
    block.append("/* == COMPOSED LAYER (machine-generated from domain DNA) ==")
    block.append("   Generated by composer.py; applied by apply.py.")
    block.append("   Existing project variables untouched; new scopes below. */")
    block.extend(lines_out)
    block.append("")
    block.append(composed_motion)
    return css + "\n".join(block) + "\n", added


def apply_project(existing_css, composed_tokens, composed_motion):
    report = {"changes": []}
    css, removed = remove_tells(existing_css)
    report["removed_tells"] = removed
    if removed:
        report["changes"].append("removed %d glassmorphism backdrop-filter lines" % len(removed))
    css, fixed_card = fix_glass_card(css)
    if fixed_card:
        report["changes"].append(".glass-card: glass -> opaque parchment-sheet material (class name kept)")
    css, added = inject_composed_layer(css, composed_tokens, composed_motion)
    report["added_vars"] = added
    if added:
        report["changes"].append("layered %d composed tokens (petal radius, descent spacing, breath rhythm)" % len(added))
    report["css"] = css
    return report


if __name__ == "__main__":
    import sys
    existing = open(sys.argv[1]).read()
    tokens = open(sys.argv[2]).read()
    motion = open(sys.argv[3]).read()
    rep = apply_project(existing, tokens, motion)
    open(sys.argv[4], "w").write(rep["css"])
    print(json.dumps({k: v for k, v in rep.items() if k != "css"}, ensure_ascii=False, indent=1))
