"""
design_generator.py — generates actual CSS from a derived design language.

This is the realization step: it takes the design decisions from
design_language.py and converts them into concrete CSS values.

The key: design decisions are mapped to actual values through a
decision-to-value mapping, so the output is concrete and usable.
"""

# Decision-to-value mappings: convert design decisions to actual CSS values
PALETTE_VALUES = {
    "parchment": {
        "--surface-0": "#e8dfc8",
        "--surface-1": "#ede6d4",
        "--surface-2": "#f2ecdf",
        "--surface-3": "#f6f2e9",
        "--ink": "#1a1612",
        "--ink-soft": "#544e45",
        "--ink-faint": "#857f71",
        "--accent": "#8a5a2b",
    },
    "forge": {
        "--surface-0": "#1c1815",
        "--surface-1": "#2a2522",
        "--surface-2": "#383330",
        "--surface-3": "#46413d",
        "--ink": "#e8cda5",
        "--ink-soft": "#af9a7d",
        "--ink-faint": "#7e6f5a",
        "--accent": "#de7a2a",
    },
    "ocean": {
        "--surface-0": "#0a1628",
        "--surface-1": "#122036",
        "--surface-2": "#1a2a44",
        "--surface-3": "#223452",
        "--ink": "#d0e4f0",
        "--ink-soft": "#8fb3cc",
        "--ink-faint": "#5a7a94",
        "--accent": "#2dd4bf",
    },
    "forest": {
        "--surface-0": "#0e1a12",
        "--surface-1": "#16241a",
        "--surface-2": "#1e2e22",
        "--surface-3": "#26382a",
        "--ink": "#d8e8d8",
        "--ink-soft": "#94b894",
        "--ink-faint": "#5a8a5a",
        "--accent": "#6db36d",
    },
    "stone": {
        "--surface-0": "#1c1c1e",
        "--surface-1": "#262628",
        "--surface-2": "#303032",
        "--surface-3": "#3a3a3c",
        "--ink": "#d8d8d6",
        "--ink-soft": "#949492",
        "--ink-faint": "#5a5a58",
        "--accent": "#8a8a9c",
    },
}

FONT_STACKS = {
    "mystical": {
        "--font-display": "'David Libre', 'Frank Ruhl Libre', serif",
        "--font-body": "'Frank Ruhl Libre', 'David Libre', serif",
    },
    "industrial": {
        "--font-display": "'Heebo', sans-serif",
        "--font-body": "'Heebo', sans-serif",
    },
    "organic": {
        "--font-display": "'Secular One', sans-serif",
        "--font-body": "'Heebo', sans-serif",
    },
    "scholarly": {
        "--font-display": "'Frank Ruhl Libre', serif",
        "--font-body": "'Heebo', sans-serif",
    },
}


def generate_palette_css(palette_material):
    """Generate CSS custom properties for the palette."""
    values = PALETTE_VALUES.get(palette_material, PALETTE_VALUES["parchment"])
    lines = [f"  {k}: {v};" for k, v in values.items()]
    return "\n".join(lines)


def generate_typography_css(character):
    """Generate CSS custom properties for typography."""
    fonts = FONT_STACKS.get(character, FONT_STACKS["scholarly"])
    lines = [f"  {k}: {v};" for k, v in fonts.items()]
    return "\n".join(lines)


def generate_design_css(design_language):
    """Generate a complete CSS design system from a design language.
    Returns a CSS string with custom properties.
    """
    palette = design_language["dimensions"]["palette"]
    typography = design_language["dimensions"]["typography"]

    css_lines = []
    css_lines.append("/* Design System — derived from project identity */")
    css_lines.append("/* Generated by design_generator.py */")
    css_lines.append("")
    css_lines.append(":root {")
    css_lines.append("  /* Palette: " + palette.get("logic", "") + " */")
    css_lines.append(generate_palette_css(palette.get("material", "parchment")))
    css_lines.append("")
    css_lines.append("  /* Typography: " + typography.get("logic", "") + " */")
    css_lines.append(generate_typography_css(typography.get("character", "scholarly")))
    css_lines.append("}")
    css_lines.append("")

    return "\n".join(css_lines)


if __name__ == "__main__":
    # Test with a sample design language
    from design_language import derive_design_language
    identity = {
        "motifs": ["tree of life", "light", "mystery"],
        "materials": ["parchment"],
        "character": "mystical scholarly",
    }
    lang = derive_design_language(identity)
    css = generate_design_css(lang)
    print(css)
