import sys
import json

# pagegen.py — generates a COMPLETE landing page from a design system.
# Nav + Hero + Features + Quote + Pricing + CTA + Footer, all on design tokens,
# with the tension elements embedded (2px quote border, accent pricing tier,
# asymmetric hero spacing, lowercase headings).

PAGE_TSX = 'import Nav from "../anti-ai-components/components/Nav";\nimport Hero from "../anti-ai-components/components/Hero";\nimport Button from "../anti-ai-components/components/Button";\nimport Card from "../anti-ai-components/components/Card";\n\n// Complete landing page — concept: {{CONCEPT}}\n// Generated by the Anti-AI Design System. Tension points:\n// - Hero uses --section-top / --section-bottom (asymmetric spacing)\n// - The quote block carries the one 2px border\n// - The middle pricing tier gets the accent border\n// - Headings lowercase. Do not "fix" these.\nexport default function LandingPage() {\n  return (\n    <div style={{ background: "var(--color-surface)", color: "var(--color-text)" }}>\n      <Nav\n        logo="{{LOGO}}"\n        links={[\n          { label: "features", href: "#features" },\n          { label: "pricing", href: "#pricing" },\n          { label: "about", href: "#about" },\n        ]}\n        cta="start"\n      />\n      <Hero\n        title="{{HEADLINE}}"\n        subtitle="{{SUBTITLE}}"\n        primaryCta="{{CTA_BUTTON}}"\n        secondaryCta="see pricing"\n      />\n\n      <section id="features" style={{ maxWidth: 1200, margin: "0 auto", padding: "48px 24px" }}>\n        <h2 style={{ fontFamily: "var(--font-display)", fontSize: 28, letterSpacing: "var(--tracking-display)", marginTop: 0, marginBottom: 24 }}>\n          what you get\n        </h2>\n        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 16 }}>\n          <Card title="{{F1_TITLE}}">{{F1_TEXT}}</Card>\n          <Card title="{{F2_TITLE}}" variant="tension">{{F2_TEXT}}</Card>\n          <Card title="{{F3_TITLE}}">{{F3_TEXT}}</Card>\n        </div>\n      </section>\n\n      <section id="about" style={{ maxWidth: 900, margin: "0 auto", padding: "32px 24px" }}>\n        <blockquote style={{ border: "2px solid var(--color-tension)", borderRadius: "var(--radius-md)", padding: 32, margin: 0 }}>\n          <p style={{ fontFamily: "var(--font-display)", fontSize: 22, lineHeight: 1.4, marginTop: 0, marginBottom: 12 }}>\n            "{{QUOTE}}"\n          </p>\n          <cite style={{ fontFamily: "var(--font-body)", fontSize: 13, color: "var(--color-text-muted)", fontStyle: "normal" }}>\n            — {{QUOTE_AUTHOR}}\n          </cite>\n        </blockquote>\n      </section>\n\n      <section id="pricing" style={{ maxWidth: 1200, margin: "0 auto", padding: "48px 24px" }}>\n        <h2 style={{ fontFamily: "var(--font-display)", fontSize: 28, letterSpacing: "var(--tracking-display)", marginTop: 0, marginBottom: 24 }}>\n          pricing\n        </h2>\n        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 16 }}>\n          {["{{TIER1}}", "{{TIER2}}", "{{TIER3}}"].map((tier, i) => (\n            <div\n              key={tier}\n              style={{\n                background: "var(--color-surface)",\n                border: i === 1 ? "2px solid var(--color-accent)" : "1px solid var(--color-border)",\n                borderRadius: "var(--radius-md)",\n                padding: 24,\n                textAlign: "center",\n              }}\n            >\n              <p style={{ fontFamily: "var(--font-display)", fontSize: 18, marginTop: 0, marginBottom: 8 }}>{tier}</p>\n              <p style={{ fontFamily: "var(--font-body)", fontSize: 13, color: "var(--color-text-muted)", marginBottom: 16 }}>\n                for teams that care\n              </p>\n              <Button variant={i === 1 ? "primary" : "secondary"}>{i === 1 ? "choose" : "pick"}</Button>\n            </div>\n          ))}\n        </div>\n      </section>\n\n      <section style={{ maxWidth: 1200, margin: "0 auto", padding: "64px 24px 96px", textAlign: "center" }}>\n        <h2 style={{ fontFamily: "var(--font-display)", fontSize: 32, letterSpacing: "var(--tracking-display)", marginTop: 0, marginBottom: 16 }}>\n          {{CTA_HEADLINE}}\n        </h2>\n        <Button>{{CTA_BUTTON}}</Button>\n      </section>\n\n      <footer style={{ borderTop: "1px solid var(--color-border)", padding: 24, textAlign: "center" }}>\n        <p style={{ fontFamily: "var(--font-body)", fontSize: 12, color: "var(--color-text-muted)", margin: 0 }}>\n          {{LOGO}} — built with the anti-ai design system. do not remove the tension.\n        </p>\n      </footer>\n    </div>\n  );\n}\n'

CONCEPT_COPY = {
    "workbench": {
        "logo": "workbench", "headline": "tools for people who build",
        "subtitle": "No funnels, no growth hacks. Just solid software that respects your time.",
        "f1_title": "solid defaults", "f1_text": "Sensible settings that never need configuring.",
        "f2_title": "honest pricing", "f2_text": "You pay for what you use. Nothing floats in.",
        "f3_title": "no lock-in", "f3_text": "Export everything, anytime. Your work stays yours.",
        "quote": "It feels like a good hammer. You stop thinking about it and just build.",
        "quote_author": "a freelancer who stopped fighting their tools",
        "tier1": "solo", "tier2": "crew", "tier3": "workshop",
        "cta_headline": "start building today", "cta_button": "open the bench",
    },
    "clay": {
        "logo": "clay", "headline": "shaped by hand, made to last",
        "subtitle": "Software with the warmth of something thrown on a wheel - imperfect on purpose, durable by design.",
        "f1_title": "slow craft", "f1_text": "We ship when it is right, not when the quarter ends.",
        "f2_title": "natural texture", "f2_text": "Interfaces that feel like material, not glass.",
        "f3_title": "fired to last", "f3_text": "Built for years of daily hands, not a launch week.",
        "quote": "The first tool that feels like it was made by a person.",
        "quote_author": "a designer tired of templates",
        "tier1": "studio", "tier2": "kiln", "tier3": "gallery",
        "cta_headline": "put your hands on it", "cta_button": "try the clay",
    },
    "ember": {
        "logo": "ember", "headline": "warmth in every detail",
        "subtitle": "A product that glows quietly. Careful type, honest color, nothing that shouts.",
        "f1_title": "quiet warmth", "f1_text": "Comfort without kitsch. Cozy, never cute.",
        "f2_title": "steady glow", "f2_text": "Performance that never flickers under load.",
        "f3_title": "kept alive", "f3_text": "Support from people who answer on the first try.",
        "quote": "Like working by a fire instead of a fluorescent tube.",
        "quote_author": "someone who noticed the difference",
        "tier1": "spark", "tier2": "flame", "tier3": "hearth",
        "cta_headline": "come sit by it", "cta_button": "light it up",
    },
    "caliper": {
        "logo": "caliper", "headline": "measured twice, shipped once",
        "subtitle": "Precision tooling for teams that care about the millimeter.",
        "f1_title": "exact by default", "f1_text": "Precision without ceremony or plugins.",
        "f2_title": "zero drift", "f2_text": "Your numbers stay aligned across every export.",
        "f3_title": "certified output", "f3_text": "Reports you can sign and hand to an auditor.",
        "quote": "The only tool our QA team never files tickets against.",
        "quote_author": "an engineering lead with standards",
        "tier1": "gauge", "tier2": "caliper", "tier3": "micrometer",
        "cta_headline": "measure the difference", "cta_button": "start measuring",
    },
    "tide": {
        "logo": "tide", "headline": "calm software for busy people",
        "subtitle": "Work that flows in and out without noise. Nothing pulls. Nothing nags.",
        "f1_title": "gentle rhythm", "f1_text": "Notifications that wait until you surface.",
        "f2_title": "clear water", "f2_text": "One screen, no maze. Depth without clutter.",
        "f3_title": "receding chores", "f3_text": "Automation that quietly cleans up after you.",
        "quote": "My calendar stopped screaming. So did I.",
        "quote_author": "a burned-out PM who recovered",
        "tier1": "cove", "tier2": "bay", "tier3": "open sea",
        "cta_headline": "let it carry you", "cta_button": "drift in",
    },
    "forge": {
        "logo": "forge", "headline": "built under pressure",
        "subtitle": "For teams shipping heavy things fast. Strong edges, no ornament.",
        "f1_title": "hammered flat", "f1_text": "Zero unnecessary steps between you and done.",
        "f2_title": "quenched hard", "f2_text": "Survives your worst day without bending.",
        "f3_title": "welded seams", "f3_text": "Integrations that hold when the load spikes.",
        "quote": "We migrated in a weekend. It did not blink.",
        "quote_author": "a CTO mid-deadline",
        "tier1": "anvil", "tier2": "forge", "tier3": "foundry",
        "cta_headline": "strike while it is hot", "cta_button": "enter the forge",
    },
    "vault": {
        "logo": "vault", "headline": "quiet security, serious craft",
        "subtitle": "What matters stays private. The interface stays out of the way.",
        "f1_title": "heavy doors", "f1_text": "Encryption without friction or popups.",
        "f2_title": "soft light", "f2_text": "Readable in the dark, gentle in the day.",
        "f3_title": "counted keys", "f3_text": "Access you can audit down to the person.",
        "quote": "Compliance approved it in one meeting. That never happens.",
        "quote_author": "a security officer, pleasantly surprised",
        "tier1": "ledger", "tier2": "vault", "tier3": "archive",
        "cta_headline": "put it somewhere safe", "cta_button": "open the vault",
    },
    "craft": {
        "logo": "craft", "headline": "made carefully, on purpose",
        "subtitle": "Every pixel chosen, none generated. A tool with fingerprints on it.",
        "f1_title": "hand-set type", "f1_text": "Typography with intent at every size.",
        "f2_title": "honest materials", "f2_text": "No dark patterns. Nothing pretends to be free.",
        "f3_title": "signed work", "f3_text": "We stand behind every release by name.",
        "quote": "You can tell a person made this. That is rarer than it should be.",
        "quote_author": "a user who reads changelogs",
        "tier1": "apprentice", "tier2": "journeyman", "tier3": "master",
        "cta_headline": "work with something made", "cta_button": "start crafting",
    },
}


def generate_page(design, brief=None):
    concept = (design or {}).get("concept") or "craft"
    copy = dict(CONCEPT_COPY.get(concept, CONCEPT_COPY["craft"]))
    if brief and isinstance(brief.get("project"), str) and brief["project"].strip():
        first = brief["project"].strip().split(" ")[0].lower()
        if first.isalnum():
            copy["logo"] = first
    page = PAGE_TSX.replace("{{CONCEPT}}", concept)
    for key in sorted(copy.keys(), key=len, reverse=True):
        page = page.replace("{{" + key.upper() + "}}", str(copy[key]))
    return {
        "page/landing-page.tsx": page,
        "page/content.json": json.dumps(copy, indent=2),
    }


def generate_all_pages(design, brief=None):
    files = generate_page(design, brief)
    total_lines = sum(len(c.splitlines()) for c in files.values())
    return {"files": files, "file_count": len(files), "total_lines": total_lines}


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print('usage: pagegen.py \'{"concept": "workbench"}\' [brief json]')
        sys.exit(1)
    design = json.loads(sys.argv[1])
    brief = json.loads(sys.argv[2]) if len(sys.argv) > 2 else None
    result = generate_all_pages(design, brief)
    print(json.dumps({"file_count": result["file_count"], "total_lines": result["total_lines"],
                      "page_preview": result["files"]["page/landing-page.tsx"][:600]}, indent=2))
